# -*- coding: utf-8 -*-
# Batch 3: Bai 11 to Bai 15

BATCH_MAP = {
    # Bai 11
    "1. Cấp clock cho GPIOA và ADC1 trên bus APB2": "1. Enable clocks for GPIOA and ADC1 on APB2 bus",
    "1. Cấp xung clock": "1. Enable clocks",
    "2. Cấu hình PA0: Analog Mode": "2. Configure PA0: Analog Mode",
    "2. Cấu hình bộ chia tần số ADC: APB2 (72MHz) chia 6 = 12MHz (<= 14MHz)": "2. Configure ADC prescaler: APB2 (72MHz) / 6 = 12MHz (<= 14MHz max)",
    "3. Cấu hình ADC": "3. Configure ADC",
    "3. Cấu hình chân PA0 ở chế độ Analog Input": "3. Configure PA0 pin: Analog Input mode",
    "4. Chọn kênh 0, thứ tự 1, thời gian lấy mẫu 55.5 chu kỳ": "4. Select Channel 0, rank 1, 55.5 cycles sample time",
    "4. Cấu hình chuỗi chuyển đổi: Chỉ đo 1 kênh duy nhất": "4. Configure conversion sequence: 1 single channel",
    "5. Cho phép ngắt End of Conversion (EOC)": "5. Enable End of Conversion (EOC) interrupt",
    "5. Cấu hình thời gian lấy mẫu cho Channel 0: 55.5 chu kỳ": "5. Configure Channel 0 sample time: 55.5 cycles",
    "6. Cấu hình NVIC": "6. Configure NVIC",
    "6. Cấu hình chế độ chuyển đổi đơn (Single conversion mode)": "6. Configure Single conversion mode",
    "7. Bật nguồn cho bộ ADC (ADON = 1)": "7. Power on ADC (ADON = 1)",
    "7. Kích hoạt ADC và thực hiện hiệu chuẩn": "7. Enable ADC and perform calibration",
    "8. Bắt đầu chuyển đổi liên tục": "8. Start continuous conversion",
    "8. TIẾN HÀNH HIỆU CHUẨN PHẦN CỨNG (CALIBRATION)": "8. EXECUTE HARDWARE CALIBRATION",
    "ADON = 1 lần 2 để kích phát": "ADON = 1 second time to trigger conversion",
    "Bắt đầu chuyển đổi bằng phần mềm (SWSTART)": "Start conversion by software (SWSTART)",
    "Bắt đầu quá trình tự hiệu chuẩn": "Start calibration process",
    "Chuyển đổi liên tục": "Continuous conversion",
    "Chờ CAL tự xóa về 0": "Wait until CAL bit clears to 0",
    "Chờ RSTCAL tự xóa về 0": "Wait until RSTCAL bit clears to 0",
    "Chờ cho đến khi cờ EOC (End Of Conversion) được kéo lên 1": "Wait until EOC (End Of Conversion) flag is set to 1",
    "Chờ ổn định nguồn ADC (~ vài micro-giây)": "Wait for ADC power stabilization (~few microseconds)",
    "Căn phải dữ liệu": "Right alignment of data",
    "Cấu hình LED PC13": "Configure LED PC13",
    "Hàm phục vụ ngắt ADC1 và ADC2 dùng chung một vector ngắt": "ADC1 and ADC2 shared interrupt service routine (ISR)",
    "L[3:0] = 0000b (Độ dài chuỗi = 1 kênh)": "L[3:0] = 0000b (Sequence length = 1 channel)",
    "Reset mạch hiệu chuẩn": "Reset calibration registers",
    "SQ1 = 0 (Kênh ADC_IN0 được chọn đo đầu tiên)": "SQ1 = 0 (Channel ADC_IN0 mapped to rank 1)",
    "Thời gian trễ tỉ lệ theo giá trị ADC đo được (khoảng 50ms đến 500ms)": "Delay proportional to measured ADC value (approx 50ms to 500ms)",
    "adc_result luôn được tự động cập nhật trong ngắt ngầm": "adc_result is continuously updated in background ISR",
    "Điều khiển tốc độ nháy LED theo giá trị biến trở": "Adjust LED blink rate according to potentiometer reading",
    "Đọc giá trị chuyển đổi (Lệnh này tự động xóa cờ ngắt EOC)": "Read conversion value (This automatically clears EOC flag)",
    "Đọc kết quả đo từ thanh ghi dữ liệu ADC_DR (Đọc DR sẽ tự động xóa cờ EOC)": "Read conversion data from ADC_DR (Reading DR clears EOC flag)",
    "Đổi giá trị thô sang điện áp mili-Volt (mV)": "Convert raw value to millivolts (mV)",

    # Bai 12
    "1. Cấp clock cho GPIOA và ADC1": "1. Enable clocks for GPIOA and ADC1",
    "1. Đọc điện áp biến trở (Channel 0)": "1. Read potentiometer voltage (Channel 0)",
    "2. Chia tần số ADC: 72MHz / 6 = 12MHz": "2. ADC clock prescaler: 72MHz / 6 = 12MHz",
    "2. Đọc kênh VREFINT (Channel 17) để tính điện áp nguồn nuôi thực tế": "2. Read VREFINT channel (Channel 17) to calculate actual VDD voltage",
    "3. Cấu hình chân PA0: Analog Mode": "3. Configure PA0 pin: Analog Mode",
    "3. Đọc cảm biến nhiệt độ chip (Channel 16)": "3. Read internal chip temperature sensor (Channel 16)",
    "4. KÍCH HOẠT CẢM BIẾN NHIỆT ĐỘ NỘI & VREFINT": "4. ENABLE INTERNAL TEMPERATURE SENSOR & VREFINT",
    "5. Cấu hình thời gian lấy mẫu cực đại 239.5 chu kỳ cho Kênh 16 và Kênh 17 trong SMPR1": "5. Configure max sample time 239.5 cycles for Channels 16 & 17 in SMPR1",
    "6. Bật nguồn ADC và hiệu chuẩn": "6. Power on ADC and calibrate",
    "Bật LED PC13": "Turn on LED PC13",
    "Bắt đầu chuyển đổi": "Start conversion",
    "Chờ kết thúc chuyển đổi EOC": "Wait for conversion complete (EOC)",
    "Cấu hình chuỗi chuyển đổi: 1 kênh duy nhất": "Configure conversion sequence: 1 single channel",
    "Cấu hình kênh 16, thời gian lấy mẫu tối đa 239.5 chu kỳ": "Configure Channel 16 with max 239.5 cycles sample time",
    "Gán kênh cần đo vào SQ1": "Assign target channel to rank 1 (SQ1)",
    "Hiệu chuẩn": "Calibrate ADC",
    "Hàm đọc 1 kênh chỉ định theo yêu cầu": "Read specified channel on demand",
    "Kênh 0 lấy mẫu 55.5 chu kỳ trong SMPR2": "Channel 0 sample time 55.5 cycles in SMPR2",
    "Kích hoạt cảm biến nhiệt độ nội và kênh tham chiếu VREFINT": "Enable internal temperature sensor and VREFINT reference",
    "LED PC13 cảnh báo": "Alarm LED PC13",
    "Nếu nhiệt độ chip > 45 độ C -> Bật đèn LED cảnh báo": "If internal temp > 45 deg C -> Turn on warning LED",
    "Trễ giữa các lần đo": "Delay between measurements",
    "Tính nhiệt độ: T = (1.43 - Vsense) / 0.0043 + 25": "Calculate temperature: T = (1.43 - Vsense) / 0.0043 + 25",
    "Tính điện áp cảm biến theo nguồn nuôi thực tế:": "Calculate sensor voltage based on actual VDD supply:",
    "Tắt LED": "Turn off LED",

    # Bai 13
    "1. Cấp clock": "1. Enable clocks",
    "1. Cấp xung clock cho GPIOA, GPIOC và USART1 trên bus APB2": "1. Enable clocks for GPIOA, GPIOC, and USART1 on APB2 bus",
    "2. Cấu hình chân PA9 (TX): Alternate Function Output Push-Pull 50MHz": "2. Configure PA9 (TX): Alternate Function Output Push-Pull 50MHz",
    "2. Cấu hình chân PA9 (TX): Alternate Function Push-Pull": "2. Configure PA9 (TX): Alternate Function Push-Pull",
    "3. Cấu hình chân PA10 (RX): Input Pull-Up": "3. Configure PA10 (RX): Input Pull-Up",
    "3. Cấu hình chân PA10 (RX): Input with Pull-Up": "3. Configure PA10 (RX): Input with Pull-Up",
    "4. Cấu hình LED PC13 làm đèn báo": "4. Configure LED PC13 as indicator",
    "4. Cấu hình thông số giao tiếp USART1": "4. Configure USART1 communication parameters",
    "5. Cho phép ngắt nhận RXNE": "5. Enable RXNE receive interrupt",
    "5. Cấu hình Baud Rate trên thanh ghi USART1_BRR (Xung APB2 = 72MHz)": "5. Configure Baud Rate in USART1_BRR (APB2 clock = 72MHz)",
    "6. Cho phép ngắt khi nhận dữ liệu (RXNEIE)": "6. Enable receive data interrupt (RXNEIE)",
    "6. Cấu hình NVIC": "6. Configure NVIC",
    "7. Cấu hình NVIC cho ngắt USART1": "7. Configure NVIC for USART1 interrupt",
    "7. Kích hoạt USART1": "7. Enable USART1",
    "8. Bật bộ truyền (TE), bộ nhận (RE) và kích hoạt USART1 (UE)": "8. Enable transmitter (TE), receiver (RE), and USART1 module (UE)",
    "Bật LED PC13": "Turn on LED PC13",
    "Chờ TXE = 1": "Wait for TXE = 1",
    "Chờ bộ đệm truyền trống (TXE = 1)": "Wait until transmit data register is empty (TXE = 1)",
    "Chờ cờ TXE báo trống": "Wait until TXE flag indicates buffer empty",
    "Công thức: USARTDIV = 72000000 / (16 * baudrate)": "Formula: USARTDIV = 72000000 / (16 * baudrate)",
    "Ghi ký tự vào thanh ghi truyền": "Write character to data register",
    "Gửi 1 ký tự qua USART1": "Send 1 character via USART1",
    "Hàm phục vụ ngắt nhận ký tự USART1": "USART1 receive interrupt service routine (ISR)",
    "In thông điệp khởi động hệ thống qua printf": "Print system startup message via printf",
    "Kiểm tra cờ RXNE (Đã nhận được byte mới)": "Check RXNE flag (New byte received)",
    "Kéo trở Pull-up": "Enable internal pull-up",
    "Trễ 1 giây": "1-second delay",
    "Tái định hướng hàm fputc cho Keil C MicroLIB": "Retarget fputc for Keil C MicroLIB",
    "Tại 115200: BRR = 0x0271": "At 115200 baud: BRR = 0x0271",
    "Tắt LED": "Turn off LED",
    "Tắt LED PC13": "Turn off LED PC13",
    "Viết lại hàm fputc phục vụ Keil MDK MicroLIB": "Retarget fputc function for Keil MDK MicroLIB",
    "Xử lý lệnh nhận được": "Process received command",
    "Đọc dữ liệu từ thanh ghi DR (Đọc DR tự động xóa cờ RXNE)": "Read data from DR (Reading DR clears RXNE flag)",

    # Bai 14
    "1. Kiểm tra ngắt nhận dữ liệu (RXNE)": "1. Check RXNE receive interrupt",
    "2. Kiểm tra ngắt đường truyền nhàn rỗi (IDLE Line)": "2. Check IDLE Line interrupt",
    "BẬT CẢ HAI NGẮT: Ngắt nhận từng byte (RXNEIE) và Ngắt nhàn rỗi kết thúc gói (IDLEIE)": "ENABLE BOTH INTERRUPTS: Byte received (RXNEIE) and IDLE Line detected (IDLEIE)",
    "Bật LED (Active-Low)": "Turn on LED (Active-Low)",
    "Bật cờ báo hiệu đã nhận xong một gói tin hoàn chỉnh!": "Set packet complete flag!",
    "Bỏ qua cảnh báo biến không dùng": "Suppress unused variable warning",
    "Bộ phân tích và thực thi câu lệnh CLI": "CLI command parser and execution handler",
    "Bộ đệm rỗng": "Buffer empty",
    "Cấu hình Baudrate (72MHz)": "Configure Baudrate (72MHz)",
    "Cực kỳ nhanh, chỉ tốn 1 chu kỳ lệnh!": "Ultra-fast execution: takes only 1 instruction cycle!",
    "Ghi 1 byte vào bộ đệm vòng": "Write 1 byte into Ring Buffer",
    "Hàm phục vụ ngắt USART1": "USART1 interrupt service routine (ISR)",
    "Khi cờ ngắt IDLE báo có gói tin hoàn chỉnh hoặc người dùng vừa gõ xong": "When IDLE flag signals complete packet or keystroke finished",
    "Kiểm tra số lượng byte hiện có trong bộ đệm": "Check number of available bytes in buffer",
    "Kích hoạt TE, RE, UE": "Enable TE, RE, UE",
    "Loại bỏ các ký tự xuống dòng ở cuối chuỗi": "Trim trailing newline and carriage return characters",
    "Nếu bộ đệm chưa đầy": "If buffer is not full",
    "QUY TRÌNH XÓA CỜ IDLE BẮT BUỘC THEO RM0008:": "MANDATORY IDLE FLAG CLEARING SEQUENCE PER RM0008:",
    "So khớp câu lệnh": "Match command string",
    "Tắt LED": "Turn off LED",
    "Đẩy byte vào bộ đệm vòng": "Push byte into Ring Buffer",
    "Đọc 1 byte ra khỏi bộ đệm vòng": "Read 1 byte from Ring Buffer",
    "Đọc thanh ghi USART_SR rồi đọc tiếp thanh ghi USART_DR": "Read USART_SR followed by reading USART_DR",
    "Đọc toàn bộ dữ liệu từ Ring Buffer ra buffer xử lý": "Flush all data from Ring Buffer into processing buffer",

    # Bai 15
    "0x14 = Enable Charge Pump (Bắt buộc để màn hình phát sáng)": "0x14 = Enable Charge Pump (Required for display output)",
    "1. Cấp clock cho GPIOB và I2C1 trên bus APB1": "1. Enable clocks for GPIOB and I2C1 on APB1 bus",
    "1. Phát Start": "1. Generate START condition",
    "2. Cấu hình PB6 (SCL) và PB7 (SDA): Alternate Function Open-Drain 50MHz": "2. Configure PB6 (SCL) and PB7 (SDA): Alternate Function Open-Drain 50MHz",
    "2. Gửi địa chỉ Slave hướng Ghi": "2. Send Slave address (Write mode)",
    "3. Gửi địa chỉ thanh ghi nội": "3. Send internal register address",
    "3. Reset khối I2C1 phần cứng để giải phóng bus": "3. Reset I2C1 hardware peripheral to release bus",
    "4. Cấu hình tần số bus PCLK1 = 36MHz vào thanh ghi I2C_CR2": "4. Set PCLK1 = 36MHz bus clock in I2C_CR2 register",
    "4. Gửi dữ liệu": "4. Send data byte",
    "5. Cấu hình tốc độ Standard Mode 100kHz vào thanh ghi I2C_CCR": "5. Set Standard Mode 100kHz in I2C_CCR register",
    "5. Phát Stop": "5. Generate STOP condition",
    "6. Cấu hình thời gian sườn lên TRISE = 36 + 1 = 37": "6. Configure maximum rise time TRISE = 36 + 1 = 37",
    "7. Kích hoạt bộ I2C1 (PE = 1)": "7. Enable I2C1 peripheral (PE = 1)",
    "Byte điều khiển: 0x00 = Lệnh Command": "Control byte: 0x00 = Command mode",
    "Bơm 9 xung nhịp để ép Slave nhả đường SDA": "Clock 9 pulses to force Slave to release SDA line",
    "Bật màn hình (Display ON)": "Turn on display (Display ON)",
    "Bật mạch bơm áp Charge Pump": "Enable internal Charge Pump circuit",
    "Chờ EV5": "Wait for EV5 event (SB=1)",
    "Chờ EV6": "Wait for EV6 event (ADDR=1)",
    "Chờ EV8_2": "Wait for EV8_2 event (BTF=1)",
    "Chờ OLED khởi động nguồn": "Wait for OLED power-on stabilization",
    "Chờ cờ ADDR (Address Sent) được kéo lên 1 (EV6)": "Wait until ADDR (Address Sent) flag is set to 1 (EV6)",
    "Chờ cờ BTF (Byte Transfer Finished) báo byte đã phát xong": "Wait until BTF (Byte Transfer Finished) flag signals completion",
    "Chờ cờ SB (Start Bit) được kéo lên 1 (EV5)": "Wait until SB (Start Bit) flag is set to 1 (EV5)",
    "Chờ đệm truyền trống (TXE = 1)": "Wait until transmit buffer is empty (TXE = 1)",
    "Cấu hình I2C1": "Configure I2C1",
    "Cấu hình SCL (PB6) làm GPIO Output Open-Drain": "Configure SCL (PB6) as GPIO Output Open-Drain",
    "Gửi 1 byte dữ liệu": "Send 1 data byte",
    "Gửi 1 byte dữ liệu qua SPL kèm kiểm tra cờ sự kiện chuẩn": "Send 1 data byte via SPL with standard event checks",
    "Gửi một lệnh (Command) tới OLED SSD1306": "Send command byte to SSD1306 OLED",
    "Gửi địa chỉ Slave (7-bit + R/W)": "Send Slave address (7-bit + R/W)",
    "Khởi tạo màn hình OLED SSD1306": "Initialize SSD1306 OLED display",
    "Màn hình OLED hoạt động ổn định": "OLED display running stably",
    "PB6 (SCL) và PB7 (SDA): AF_OD": "PB6 (SCL) and PB7 (SDA): AF Open-Drain",
    "Phát điều kiện START": "Generate START condition",
    "Phát điều kiện STOP": "Generate STOP condition",
    "Tắt màn hình (Display OFF)": "Turn off display (Display OFF)",
    "XÓA CỜ ADDR: Đọc SR1 sau đó đọc SR2": "CLEAR ADDR FLAG: Read SR1 followed by reading SR2",
    "Đặt chế độ định địa chỉ bộ nhớ (Memory Addressing Mode)": "Set Memory Addressing Mode",
    "Địa chỉ 8-bit ghi của OLED SSD1306": "8-bit Write address of SSD1306 OLED",
}
