# -*- coding: utf-8 -*-
# Batch 2: Bai 06 to Bai 10

BATCH_MAP = {
    # Bai 06
    "1. Cấp xung clock cho TIM2 trên bus APB1 và GPIOC trên APB2": "1. Enable clocks for TIM2 on APB1 and GPIOC on APB2",
    "1. Cấp xung nhịp cho GPIOC và TIM2": "1. Enable clocks for GPIOC and TIM2",
    "2. Cấu hình PC13: Output Push-Pull": "2. Configure PC13: Output Push-Pull",
    "2. Cấu hình chân PC13: Output Push-Pull 2MHz": "2. Configure PC13 pin: Output Push-Pull 2MHz",
    "3. Cấu hình khối Time-base TIM2 cho ngắt 1 giây (1Hz)": "3. Configure TIM2 time-base for 1-second interrupt (1Hz)",
    "3. Cấu hình khối Time-base TIM2: 1Hz (1 giây)": "3. Configure TIM2 time-base: 1Hz (1 second)",
    "4. Bật cờ cho phép ngắt tràn Update Interrupt (UIE)": "4. Enable Update Interrupt Enable (UIE)",
    "4. Cho phép ngắt Update Event": "4. Enable Update Event interrupt",
    "5. Cấu hình NVIC": "5. Configure NVIC",
    "5. Cấu hình NVIC cho kênh ngắt TIM2": "5. Configure NVIC for TIM2 interrupt channel",
    "6. Kích hoạt TIM2": "6. Enable TIM2",
    "6. Kích hoạt bộ đếm Timer bắt đầu chạy (CEN = 1)": "6. Enable timer counter (CEN = 1)",
    "CPU hoàn toàn rảnh rỗi, có thể vào chế độ ngủ tiết kiệm điện": "CPU is completely idle, can enter low-power Sleep mode",
    "Cho phép ngắt TIM2 trong NVIC": "Enable TIM2 interrupt in NVIC",
    "Chu kỳ tràn: 10000 nhịp đếm / 10kHz = 1 giây": "Overflow period: 10000 ticks / 10kHz = 1 second",
    "Hàm phục vụ ngắt TIM2": "TIM2 interrupt service routine (ISR)",
    "Kiểm tra cờ ngắt Update Interrupt Flag (UIF)": "Check Update Interrupt Flag (UIF)",
    "Mặc định tắt LED": "Default: turn off LED",
    "XÓA CỜ NGẮT BẮT BUỘC: Ghi 0 vào bit UIF": "MANDATORY: Clear interrupt flag by writing 0 to UIF bit",
    "Xóa bộ đếm về 0": "Reset counter to 0",
    "Xóa cờ ngắt Update": "Clear Update interrupt flag",
    "Đảo trạng thái LED PC13": "Toggle LED PC13 state",
    "Đảo trạng thái chân PC13": "Toggle PC13 pin state",
    "Đếm lên": "Upcounter mode",
    "Ưu tiên ngắt mức 1": "Interrupt priority level 1",

    # Bai 07
    "1. Cấp xung nhịp cho GPIOA và TIM2": "1. Enable clocks for GPIOA and TIM2",
    "2. Cấu hình chân PA1 (TIM2_CH2): Alternate Function Push-Pull": "2. Configure PA1 pin (TIM2_CH2): Alternate Function Push-Pull",
    "3. Khối Time-base 50Hz (Chu kỳ 20ms)": "3. Time-base 50Hz (20ms period)",
    "4. Cấu hình Kênh 2 ngõ ra PWM Mode 1": "4. Configure Channel 2 PWM Output Mode 1",
    "5. Kích hoạt TIM2": "5. Enable TIM2",
    "Bật bộ đệm Preload cho Channel 2": "Enable Preload register for Channel 2",
    "Hàm chuyển đổi góc quay từ 0 đến 180 độ thành giá trị nạp CCR2": "Convert angle (0-180 deg) to CCR2 reload value",
    "Khởi tạo ở góc 90 độ (1.5ms)": "Initialize at 90 degrees (1.5ms pulse)",
    "Map từ [0 - 180] độ thành [1000 - 2000] us": "Map [0 - 180] degrees to [1000 - 2000] us",
    "Quay về 0 độ": "Rotate to 0 degrees",
    "Quay về 180 độ": "Rotate to 180 degrees",
    "Quay về 90 độ": "Rotate to 90 degrees",
    "Đếm mỗi 1us": "1us tick rate",

    # Bai 08
    "0: Chờ cạnh lên, 1: Chờ cạnh xuống, 2: Đã đo xong": "0: Wait for rising edge, 1: Wait for falling edge, 2: Measurement complete",
    "1. Cấp xung clock cho GPIOA, GPIOC và TIM3": "1. Enable clocks for GPIOA, GPIOC, and TIM3",
    "10. Bật Timer": "10. Enable Timer",
    "4. PC13: Output Push-Pull báo còi/LED cảnh báo": "4. PC13: Output Push-Pull for buzzer/LED alarm indicator",
    "5. Cấu hình khối Time-base TIM3: Đếm mỗi 1us (f = 1MHz)": "5. Configure TIM3 time-base: 1us tick (f = 1MHz)",
    "6. Cấu hình Input Capture Channel 1 trên TIM3_CCMR1": "6. Configure Input Capture Channel 1 in TIM3_CCMR1",
    "7. Cấu hình bắt cạnh lên ban đầu và kích hoạt Capture trong CCER": "7. Configure initial rising edge and enable Capture in CCER",
    "72MHz / 72 = 1MHz -> 1 nhịp = 1us": "72MHz / 72 = 1MHz -> 1 tick = 1us",
    "8. Bật ngắt Capture Kênh 1": "8. Enable Channel 1 Capture interrupt",
    "9. Cấu hình NVIC": "9. Configure NVIC",
    "Bật LED (Active-Low)": "Turn on LED (Active-Low)",
    "Bật ngắt Capture": "Enable Capture interrupt",
    "Bắt cạnh lên": "Rising edge capture",
    "CC1P = 0 (Bắt cạnh lên)": "CC1P = 0 (Capture on rising edge)",
    "CC1S = 01b (Ánh xạ TI1 vào CC1)": "CC1S = 01b (Map TI1 to CC1)",
    "Chờ đo xong hoặc quá thời gian timeout (~60ms)": "Wait for completion or timeout (~60ms)",
    "Cấu hình Input Capture Channel 1": "Configure Input Capture Channel 1",
    "Hàm phục vụ ngắt TIM3": "TIM3 interrupt service routine (ISR)",
    "IC1F = 0000b (Không lọc nhiễu số)": "IC1F = 0000b (No digital filter)",
    "Kiểm tra cờ ngắt Capture Channel 1 (CC1IF)": "Check Channel 1 Capture interrupt flag (CC1IF)",
    "Kéo chân TRIG lên mức High trong 12us": "Pull TRIG pin HIGH for 12us",
    "Mặc định hạ TRIG xuống mức 0": "Default: pull TRIG pin LOW",
    "Nếu khoảng cách gần hơn 15cm -> Bật LED cảnh báo PC13": "If distance < 15cm -> Turn on warning LED PC13",
    "Time Base: Đếm mỗi 1us": "Time Base: 1us tick rate",
    "Trả lại cấu hình bắt cạnh lên cho lần đo tiếp theo": "Restore rising edge capture for next measurement",
    "Trễ micro-giây bằng vòng lặp ngắn cho xung Trigger": "Microsecond delay using short busy-loop for Trigger pulse",
    "Tính khoảng cách": "Calculate distance",
    "Tắt LED": "Turn off LED",
    "Vừa bắt được cạnh lên của xung ECHO": "Captured rising edge of ECHO pulse",
    "Vừa bắt được cạnh xuống của xung ECHO": "Captured falling edge of ECHO pulse",
    "Xóa cờ ngắt Capture CC1IF bằng cách ghi 0": "Clear CC1IF capture flag by writing 0",
    "Xấp xỉ tại 72MHz": "Approximate at 72MHz",
    "Đo định kỳ mỗi 100ms": "Periodic measurement every 100ms",
    "Đã đo xong 1 chu kỳ": "Single cycle measurement complete",
    "Đếm tối đa 65535us (~65ms, đủ đo khoảng cách tới 4 mét)": "Count up to 65535us (~65ms, covers up to 4 meters)",
    "Đổi cấu hình sang bắt cạnh xuống (CC1P = 1)": "Switch capture polarity to falling edge (CC1P = 1)",

    # Bai 09
    "1. Cấp clock": "1. Enable clocks",
    "1. Cấp clock cho GPIOB và TIM4": "1. Enable clocks for GPIOB and TIM4",
    "2. Chân PB6, PB7: Input Pull-Up": "2. Pins PB6, PB7: Input Pull-Up",
    "2. Cấu hình PB6 và PB7: Input with Pull-Up": "2. Configure PB6 and PB7: Input with Pull-Up",
    "3. Cấu hình ánh xạ kênh ngõ vào CC1S và CC2S trong CCMR1": "3. Map input channels CC1S and CC2S in CCMR1",
    "3. Khởi tạo Time-base": "3. Initialize Time-base",
    "4. Kích hoạt tính năng Encoder Interface phần hardware": "4. Enable hardware Encoder Interface",
    "4. Kích hoạt tính năng Encoder Interface phần cứng": "4. Enable hardware Encoder Interface",
    "4. Thiết lập bộ lọc số phần cứng chống rung cơ học (Digital Filter = 6 chu kỳ clock)": "4. Configure hardware digital filter (Filter = 6 clock cycles)",
    "5. Cấu hình bộ lọc chống rung (Digital Filter)": "5. Configure digital filter",
    "5. Cấu hình cực tính (Không đảo cực: CC1P = 0, CC2P = 0)": "5. Configure polarity (Non-inverted: CC1P = 0, CC2P = 0)",
    "6. Cấu hình chế độ Encoder Mode 3 (X4: Đếm trên cả 2 cạnh TI1 và TI2)": "6. Configure Encoder Mode 3 (X4: Count on both TI1 and TI2 edges)",
    "6. Reset bộ đếm và kích hoạt Timer": "6. Reset counter and enable Timer",
    "7. Cấu hình giá trị giới hạn chu kỳ nạp lại ARR": "7. Configure ARR auto-reload register limit",
    "8. Bật Timer hoạt động": "8. Enable Timer operation",
    "Bộ chia 1 (Đếm từng cạnh xung trực tiếp)": "Prescaler /1 (Direct edge counting)",
    "Cấu hình LED PC13": "Configure LED PC13",
    "Cực tính TI1": "TI1 polarity",
    "Cực tính TI2": "TI2 polarity",
    "Xử lý giá trị xung encoder": "Process encoder tick counts",
    "Đảo LED khi có xoay encoder": "Toggle LED upon encoder rotation",
    "Đặt vị trí ban đầu về 0": "Set initial position to 0",
    "Đếm tối đa 65535": "Max count 65535",
    "Đọc bit DIR trong TIM4_CR1: 0 = Quay thuận (Tăng), 1 = Quay ngược (Giảm)": "Read DIR bit in TIM4_CR1: 0 = Forward (Up), 1 = Reverse (Down)",

    # Bai 10
    "1. Cho phép ghi vào các thanh ghi IWDG": "1. Enable write access to IWDG registers",
    "1. Kích hoạt Watchdog chạy bằng cách ghi mã lệnh 0xCCCC vào IWDG_KR": "1. Start Watchdog by writing key 0xCCCC to IWDG_KR",
    "2. Mở khóa cho phép ghi vào thanh ghi PR và RLR bằng cách ghi 0x5555": "2. Unlock write access to PR and RLR registers by writing 0x5555",
    "2. Thiết lập Prescaler: Chia 64 (Tần số nhịp đếm: 40kHz / 64 = 625Hz)": "2. Set Prescaler: /64 (Tick rate: 40kHz / 64 = 625Hz)",
    "3. Cấu hình hệ số chia tần số Prescaler": "3. Configure Prescaler divider",
    "3. Thiết lập giá trị nạp lại Reload: 624 (Timeout xấp xỉ 1000ms)": "3. Set Reload value: 624 (Approx. 1000ms timeout)",
    "4. Nạp giá trị chu kỳ timeout (tối đa 4095)": "4. Load reload timeout value (max 4095)",
    "4. Nạp lại bộ đếm": "4. Reload counter",
    "5. Chờ thanh ghi trạng thái SR báo giá trị đã nạp thành công": "5. Wait until SR indicates reload value updated",
    "5. Kích hoạt IWDG": "5. Enable IWDG",
    "6. Nạp lại giá trị ban đầu vào bộ đếm (Nuôi chó lần đầu)": "6. Reload initial counter value (Initial watchdog feed)",
    "Cho chó ăn (Refresh Watchdog)": "Feed watchdog (Refresh counter)",
    "Chớp tắt LED nhẹ nhàng mỗi chu kỳ vòng lặp": "Blink LED gently each main loop cycle",
    "Các tác vụ chính của hệ thống...": "Main system tasks...",
    "Cấp clock cho PORT A và PORT C": "Enable clocks for PORT A and PORT C",
    "Ghi mã 0xAAAA để nạp lại bộ đếm lùi": "Write 0xAAAA key to reload downcounter",
    "Hệ thống vừa bị cứu bởi Watchdog!": "System recovered by Watchdog reset!",
    "KIỂM TRA NGUYÊN NHÂN RESET TRONG THANH GHI RCC_CSR": "Check reset cause flags in RCC_CSR register",
    "Khởi tạo IWDG: Prescaler /64 (PR = 4), RLR = 624 -> Timeout = 1000ms": "Init IWDG: Prescaler /64 (PR = 4), RLR = 624 -> Timeout = 1000ms",
    "Khởi động bình thường (Cắm nguồn)": "Normal system startup (Power-on Reset)",
    "Kiểm tra xem hệ thống có bị reset bởi IWDG hay không": "Check if system was reset by IWDG",
    "Lần Reset này do IWDG kích hoạt!": "This reset was triggered by IWDG!",
    "Lệnh này cũng tự động bật nguồn dao động nội LSI": "This command also automatically starts internal LSI oscillator",
    "Nháy LED chậm báo hiệu sự cố": "Slow LED blink indicates fault condition",
    "Nuôi chó định kỳ": "Feed watchdog periodically",
    "NẾU BẤM NÚT PA0: Cố tình treo vòng lặp để test Watchdog": "IF PA0 BUTTON PRESSED: Intentionally hang loop to test Watchdog",
    "PA0: Input Pull-Up (Giả lập nút gây treo)": "PA0: Input Pull-Up (Simulate fault trigger button)",
    "Rơi vào vòng lặp vô tận, KHÔNG GỌI IWDG_Feed()": "Enter infinite loop WITHOUT calling IWDG_Feed()",
    "Sau đúng 1 giây, IWDG sẽ tự động kích hoạt RESET vi điều khiển!": "After exactly 1 second, IWDG will automatically trigger MCU RESET!",
    "Tạm dừng IWDG khi CPU bị dừng bởi Debugger": "Freeze IWDG counter when CPU is halted by Debugger",
    "Xóa các cờ reset": "Clear reset flags",
    "Xóa cờ Reset bằng cách set bit 24 (RMVF)": "Clear reset flags by setting bit 24 (RMVF)",
}
