# -*- coding: utf-8 -*-
# Batch 5: Bai 21 to Bai 26

BATCH_MAP = {
    # Bai 21
    "... [Có thể triển khai vsnprintf nếu cần in format]": "... [Implement vsnprintf if formatted printing is needed]",
    "1. Task Đọc Cảm Biến & Đẩy Vào Queue (Producer)": "1. Sensor Reader & Queue Producer Task",
    "1. TẠO HÀNG ĐỢI: Chứa tối đa 5 phần tử, mỗi phần tử có kích thước sizeof(SensorData_t)": "1. CREATE QUEUE: Max 5 items, item size sizeof(SensorData_t)",
    "2. Task Nhận Dữ Liệu Từ Queue & In Ra UART (Consumer)": "2. Queue Consumer & UART Print Task",
    "2. TẠO MUTEX BẢO VỆ CỔNG TRUYỀN THÔNG UART": "2. CREATE MUTEX TO PROTECT UART COMMUNICATIONS",
    "3. Task Xử Lý Khẩn Cấp Được Đánh Thức Bởi Ngắt Nút Nhấn": "3. Emergency Task Woken by Button Interrupt",
    "3. TẠO BINARY SEMAPHORE ĐỒNG BỘ NGẮT PHẦN CỨNG": "3. CREATE BINARY SEMAPHORE FOR HARDWARE ISR SYNC",
    "BẮT BUỘC: Trả lại Mutex sau khi in xong": "MANDATORY: Release Mutex after transmission completes",
    "Bắt đầu chạy hệ điều hành FreeRTOS": "Start FreeRTOS operating system",
    "Chờ nhận dữ liệu từ Queue vô thời hạn (portMAX_DELAY)": "Block on Queue indefinitely (portMAX_DELAY)",
    "Cấu trúc dữ liệu gói tin truyền qua Queue": "Data packet struct passed via Queue",
    "Ghi dữ liệu vào Queue, chờ tối đa 100ms nếu Queue đầy": "Post to Queue, wait up to 100ms if Queue is full",
    "Gửi vào Queue thành công": "Sent to Queue successfully",
    "Hàm phục vụ ngắt EXTI0 (Nút nhấn PA0)": "EXTI0 interrupt service routine (PA0 Button)",
    "Hàm tái định hướng printf có bảo vệ Mutex": "Mutex-protected printf retargeting function",
    "Khai báo các đối tượng IPC của FreeRTOS": "Declare FreeRTOS IPC handles",
    "Khi thức dậy: Chiếm Mutex in cảnh báo": "Upon wakeup: Take Mutex to print emergency alert",
    "Khởi tạo phần cứng (GPIO, UART1, EXTI0)": "Hardware initialization (GPIO, UART1, EXTI0)",
    "Kiểm tra khởi tạo tài nguyên bộ nhớ": "Verify memory resource allocation",
    "Lấy Mutex bảo vệ cổng UART trước khi in": "Acquire Mutex to guard UART port before printing",
    "Lấy mẫu mỗi 500ms": "Sample every 500ms",
    "Ngủ chờ Semaphore từ hàm ngắt ISR đánh thức": "Block waiting for Semaphore given by ISR",
    "Nháy nhanh LED PC13 cảnh báo": "Fast blink LED PC13 alarm",
    "PHÁT CỜ BÁO HIỆU CHO TASK TỪ BÊN TRONG HÀM NGẮT ISR": "SIGNAL TASK FROM WITHIN INTERRUPT SERVICE ROUTINE",
    "Thu thập dữ liệu": "Data acquisition",
    "Tạo các Task với các mức ưu tiên khác nhau": "Create tasks with distinct priority levels",
    "Xóa cờ ngắt": "Clear interrupt flag",
    "Yêu cầu chuyển ngữ cảnh ngay lập tức nếu Task vừa được đánh thức có độ ưu tiên cao hơn": "Yield immediately if woken task has higher priority than current task",
    "Ưu tiên cao nhất": "Highest priority",

    # Bai 22
    "1. Handle của Event Group": "1. Event Group Handle",
    "1. Hàm Callback của Software Timer: Chớp tắt LED PC13 mỗi 500ms": "1. Software Timer Callback: Toggle LED PC13 every 500ms",
    "1. TẠO EVENT GROUP": "1. CREATE EVENT GROUP",
    "2. Các bit cần chờ (ALL_SYSTEMS_BITS)": "2. Bits to wait for (ALL_SYSTEMS_BITS)",
    "2. Task Giả Lập Khởi Động Cảm Biến": "2. Simulated Sensor Startup Task",
    "2. TẠO SOFTWARE TIMER CHU KỲ 500ms TỰ ĐỘNG LẶP LẠI (pdTRUE = Auto-reload)": "2. CREATE 500ms AUTO-RELOAD SOFTWARE TIMER (pdTRUE = Auto-reload)",
    "3. Task Giả Lập Khởi Động Bộ Nhớ Flash": "3. Simulated Flash Storage Startup Task",
    "3. TẠO CÁC TASK": "3. CREATE TASKS",
    "3. pdTRUE: Xóa các bit về 0 sau khi chờ xong": "3. pdTRUE: Clear bits on exit after conditions met",
    "4. Task Quản Lý Hệ Thống: Chờ ĐỦ 2 ĐIỀU KIỆN MỚI CHẠY (Logic AND)": "4. System Manager Task: Wait for BOTH conditions (Logic AND)",
    "4. pdTRUE: Chờ TẤT CẢ các bit (Logic AND)": "4. pdTRUE: Wait for ALL bits (Logic AND)",
    "5. Task Xử Lý Khẩn Cấp Dùng Kỹ Thuật TASK NOTIFICATIONS (Zero-RAM)": "5. Emergency Task Using TASK NOTIFICATIONS (Zero-RAM)",
    "5. portMAX_DELAY: Chờ vô thời hạn": "5. portMAX_DELAY: Wait indefinitely",
    "Bật bit 0 trong Event Group": "Set bit 0 in Event Group",
    "Bật bit 1 trong Event Group": "Set bit 1 in Event Group",
    "Chờ nhận tín hiệu thông báo từ hàm ngắt ISR": "Wait for Task Notification from ISR",
    "Giả lập thời gian kiểm tra Flash mất 2 giây": "Simulate 2-second Flash self-test delay",
    "Giả lập thời gian nạp cảm biến mất 1 giây": "Simulate 1-second Sensor initialization delay",
    "GỬI THÔNG BÁO TRỰC TIẾP ĐẾN TASK QUA HANDLE (Không cần Semaphore!)": "SEND NOTIFICATION DIRECTLY TO TASK VIA HANDLE (No Semaphore overhead!)",
    "Hoàn thành nhiệm vụ, tự xóa Task": "Task complete, delete self",
    "HÀM CHỜ EVENT GROUP: xEventGroupWaitBits()": "WAIT FOR EVENT GROUP: xEventGroupWaitBits()",
    "Hệ thống chính vận hành ở đây": "Main system operation runs here",
    "Khởi tạo phần cứng (LED PC13, UART1, EXTI0)": "Hardware initialization (LED PC13, UART1, EXTI0)",
    "Khởi động hệ điều hành": "Start operating system",
    "Kích hoạt Software Timer chạy": "Start Software Timer",
    "Lưu lại Handle của Task để ngắt gửi Task Notification trực tiếp": "Save Task Handle for direct notification from ISR",
    "Ngắt ngoài nút bấm PA0": "External interrupt from PA0 button",
    "Tham số:": "Parameters:",
    "Tự xóa Task": "Delete current task",
    "pdTRUE: Tự động xóa bộ đếm thông báo về 0 sau khi nhận": "pdTRUE: Automatically clear notification count to 0 after read",
    "Đảo trạng thái LED PC13": "Toggle LED PC13 state",
    "Định nghĩa các bit sự kiện": "Define event bit masks",

    # Bai 23
    "(Bỏ dòng này khi chạy với module TJA1050 thật)": "(Omit this line when using physical TJA1050 transceiver)",
    "- Tự động truyền lại khi lỗi (NART = 0)": "- Automatic retransmission on error (NART = 0)",
    "- Tự động đánh thức khi có tín hiệu bus (AWUM = 1)": "- Automatic bus wakeup enabled (AWUM = 1)",
    "1. Cấp clock cho GPIOA và CAN1 trên bus APB1": "1. Enable clocks for GPIOA and CAN1 on APB1 bus",
    "1. Cấu hình ID 11-bit trong thanh ghi TIR (Bits 31-21)": "1. Configure 11-bit Standard ID in TIR (Bits 31-21)",
    "2. Cấu hình chân PA11 (CAN_RX): Input with Pull-Up": "2. Configure PA11 (CAN_RX): Input with Pull-Up",
    "2. Nạp độ dài dữ liệu (DLC)": "2. Set Data Length Code (DLC)",
    "3. Cấu hình chân PA12 (CAN_TX): Alternate Function Push-Pull 50MHz": "3. Configure PA12 (CAN_TX): AF Output Push-Pull 50MHz",
    "3. Nạp tối đa 8 byte dữ liệu vào 2 thanh ghi TDLR và TDHR": "3. Load up to 8 data bytes into TDLR and TDHR registers",
    "4. Kích hoạt phát tin bằng cách bật bit TXRQ trong TIR": "4. Trigger transmission by setting TXRQ bit in TIR",
    "4. YÊU CẦU VÀO CHẾ ĐỘ KHỞI TẠO (Initialization Mode)": "4. REQUEST INITIALIZATION MODE (INRQ = 1)",
    "5. Cấu hình các tính năng trong CAN_MCR:": "5. Configure features in CAN_MCR:",
    "6. CẤU HÌNH TỐC ĐỘ 500kbps TRÊN THANH GHI CAN_BTR (Bus APB1 = 36MHz)": "6. CONFIGURE 500kbps BIT TIMING IN CAN_BTR (APB1 Clock = 36MHz)",
    "7. YÊU CẦU THOÁT CHẾ ĐỘ KHỞI TẠO, BẮT ĐẦU HOẠT ĐỘNG": "7. EXIT INITIALIZATION MODE, START NORMAL OPERATION",
    "8. CẤU HÌNH BỘ LỌC PHẦN CỨNG (FILTER BANK 0) CHO PHÉP NHẬN TẤT CẢ ID": "8. CONFIGURE FILTER BANK 0 TO ACCEPT ALL IDENTIFIERS",
    "ABOM = 1 (Tự động phục hồi khi bị lỗi Bus-Off)": "ABOM = 1 (Automatic Bus-Off Management)",
    "Chế độ Mask Mode": "Identifier Mask Mode",
    "Chọn: Prescaler (BRP) = 4, Time Segment 1 (TS1) = 12, Time Segment 2 (TS2) = 5": "Settings: Prescaler (BRP) = 4, Time Segment 1 (TS1) = 12, Time Segment 2 (TS2) = 5",
    "Chờ INAK = 0": "Wait for INAK = 0",
    "Chờ xác nhận cờ INAK = 1": "Wait until INAK flag = 1",
    "FIFO rỗng": "FIFO empty",
    "FINIT = 0 (Thoát cấu hình bộ lọc)": "FINIT = 0 (Exit filter initialization)",
    "FINIT = 1 (Vào chế độ cấu hình bộ lọc)": "FINIT = 1 (Enter filter initialization)",
    "Giải phóng hộp thư FIFO 0 bằng cách set bit RFOM0 = 1": "Release FIFO 0 output mailbox by setting RFOM0 = 1",
    "Gán vào FIFO 0": "Assign to FIFO 0",
    "Gửi gói tin CAN với ID 0x123": "Transmit CAN message with ID 0x123",
    "Gửi một khung tin CAN 2.0A (Standard ID 11-bit)": "Transmit CAN 2.0A frame (11-bit Standard ID)",
    "Gửi thành công vào hộp thư": "Message queued in mailbox successfully",
    "Hộp thư đang bận": "Mailbox busy",
    "Kiểm tra xem FIFO 0 có tin nhắn nào không (Bits 1-0 trong RF0R > 0)": "Check if FIFO 0 contains messages (Bits 1-0 in RF0R > 0)",
    "Kiểm tra xem Hộp thư truyền Mailbox 0 có rỗng không (TME0 = 1 trong TSR)": "Check if Transmit Mailbox 0 is empty (TME0 = 1 in TSR)",
    "Kích hoạt lại Filter 0": "Reactivate Filter 0",
    "Mask = 0 (Chấp nhận tất cả ID)": "Mask = 0 (Accept all IDs)",
    "Nhận gói tin trong chế độ Loopback": "Receive message in Loopback mode",
    "Nhận khung tin từ FIFO 0": "Receive frame from FIFO 0",
    "RTR = 0 (Khung dữ liệu Data Frame)": "RTR = 0 (Data Frame)",
    "THỬ NGHIỆM: Bật chế độ Loopback để test nội bộ không cần dây nối": "TEST MODE: Enable Loopback mode for internal loopback without wires",
    "Thoát Sleep Mode (SLEEP = 0)": "Exit Sleep Mode (SLEEP = 0)",
    "Tần số baud = 36MHz / (BRP * (1 + TS1 + TS2))": "Baud rate = 36MHz / (BRP * (1 + TS1 + TS2))",
    "Tổng số time quanta (tq) = 1 + 12 + 5 = 18 tq": "Total time quanta (tq) = 1 + 12 + 5 = 18 tq",
    "Vô hiệu hóa Filter 0 để sửa đổi": "Deactivate Filter 0 for modification",
    "Đảo LED PC13 báo nhận thành công!": "Toggle LED PC13 indicating successful reception!",
    "Đọc 8 bytes dữ liệu": "Read 8 data bytes",
    "Đọc ID": "Read ID",
    "Đọc độ dài": "Read data length",
    "Độ rộng 32-bit (1 Single 32-bit filter)": "32-bit scale configuration (1 Single 32-bit filter)",

    # Bai 24
    "(Sử dụng hàm của thư viện USB-FS Device: UserToPMABufferCopy)": "(Using USB-FS Device library function: UserToPMABufferCopy)",
    "... [Cấu hình Flash Latency 2, HSE, PLL x9 như Bài 03] ...": "... [Configure Flash Latency 2, HSE, PLL x9 as in Lesson 03] ...",
    "Bit 22: USBPRE = 0 -> PLL clock chia 1.5 (72MHz / 1.5 = ĐÚNG 48MHz!)": "Bit 22: USBPRE = 0 -> PLL divided by 1.5 (72MHz / 1.5 = EXACT 48MHz!)",
    "Chờ máy tính hoàn tất quá trình nhận dạng Enumeration (~2 giây)": "Wait for host USB Enumeration to complete (~2 seconds)",
    "Con lăn cuộn trang": "Wheel scroll value",
    "CẤU HÌNH BỘ CHIA XUNG USB TRONG THANH GHI RCC_CFGR:": "CONFIGURE USB PRESCALER IN RCC_CFGR:",
    "Cấp clock cho khối ngoại vi USB trên bus APB1": "Enable peripheral clock for USB on APB1 bus",
    "Cấu hình SYSCLK = 72MHz từ HSE 8MHz": "Configure SYSCLK = 72MHz from 8MHz HSE",
    "Gửi lệnh dịch chuyển chuột lên máy tính": "Send mouse displacement packet to host",
    "Hàm gửi báo cáo chuột lên máy tính qua Endpoint 1 IN": "Send mouse HID report to host via Endpoint 1 IN",
    "Khởi tạo phần cứng và bộ đệm USB": "Initialize USB hardware and endpoints",
    "Tính toán tọa độ vi phân theo hàm lượng giác để vẽ hình tròn": "Calculate differential coordinates with trigonometric functions to draw a circle",
    "Tần số gửi báo cáo chuột: 20ms một lần (50Hz)": "Mouse report update rate: every 20ms (50Hz)",
    "Tọa độ tương đối trục X (-127 đến +127)": "Relative X displacement (-127 to +127)",
    "Tọa độ tương đối trục Y (-127 đến +127)": "Relative Y displacement (-127 to +127)",
    "Đẩy 4 bytes dữ liệu vào bộ đệm Endpoint 1 IN của USB": "Copy 4 report bytes into USB Endpoint 1 IN buffer",
    "Định nghĩa cấu trúc báo cáo của chuột USB (4 Bytes)": "Define USB Mouse HID Report structure (4 Bytes)",

    # Bai 25
    "1. KIỂM TRA TÍNH HỢP LỆ CỦA NGĂN XẾP ỨNG DỤNG (Nằm trong RAM 20KB)": "1. VERIFY VALID APPLICATION STACK POINTER (Within 20KB RAM)",
    "2. VÔ HIỆU HÓA TOÀN BỘ NGẮT VÀ RESET KHỐI RCC VỀ XUẤT XƯỞNG": "2. DISABLE ALL INTERRUPTS AND RESET RCC TO DEFAULT",
    "3. CHUYỂN HƯỚNG BẢNG VECTOR NGẮT (VECTOR TABLE RELOCATION)": "3. VECTOR TABLE RELOCATION TO APPLICATION BASE",
    "4. CÀI ĐẶT LẠI CON TRỎ NGĂN XẾP CHÍNH (MSP) CỦA ỨNG DỤNG": "4. SET MAIN STACK POINTER (MSP) TO APPLICATION STACK",
    "5. NHẢY VÀO HÀM RESET_HANDLER CỦA ỨNG DỤNG CHÍNH": "5. JUMP TO APPLICATION Reset_Handler",
    "Chớp tắt LED PC13 cực nhanh báo hiệu đang ở chế độ Bootloader": "Rapid LED PC13 blink indicates Bootloader mode active",
    "Chờ nhận dữ liệu file .bin qua UART và ghi vào Flash từ địa chỉ 0x08003000...": "Wait for .bin firmware file via UART and flash starting from 0x08003000...",
    "Cấm toàn bộ ngắt hệ thống": "Disable all global interrupts",
    "Cấp clock PORT A và PORT C": "Enable clocks for PORT A and PORT C",
    "Gọi hàm, vĩnh viễn chuyển quyền điều khiển sang Application!": "Call jump vector, permanently transferring execution to Application!",
    "Khai báo con trỏ hàm không đối số và không trả về": "Function pointer without arguments and return type",
    "Khớp chính xác với độ lệch địa chỉ Flash": "Matches application Flash address offset",
    "Khởi tạo UART để hiển thị trạng thái...": "Initialize UART for console debug output...",
    "Kiểm tra nút nhấn PA0": "Check PA0 button state",
    "Nút nhấn PA0: Input Pull-Up": "PA0 button: Input Pull-Up",
    "NẾU BẤM GIỮ NÚT PA0 -> Ở lại chế độ nạp Firmware Bootloader Mode": "IF PA0 IS HELD DOWN -> Stay in Firmware Bootloader Mode",
    "Nếu KHÔNG bấm nút PA0 (chân ở mức 1) -> Nhảy sang Application ngay!": "IF PA0 NOT PRESSED (pin is HIGH) -> Jump to Application immediately!",
    "Tắt SysTick Timer": "Disable SysTick Timer",
    "Vô hiệu hóa toàn bộ các ngắt trong NVIC": "Disable all interrupt channels in NVIC",
    "Xóa cờ cho phép ngắt": "Clear interrupt enable registers",
    "Xóa cờ chờ ngắt": "Clear pending interrupt registers",
    "Đèn LED PC13": "LED PC13 indicator",
    "Đưa cấu hình RCC về mặc định HSI": "Reset RCC configuration to default HSI",
    "Địa chỉ bắt đầu của phân vùng Ứng dụng": "Application partition base address",

    # Bai 26
    "(Thay thế hàm HardFault_Handler rỗng trong file stm32f10x_it.c)": "(Replaces dummy HardFault_Handler in stm32f10x_it.c)",
    "BFARVALID = Bit 15 của CFSR": "BFARVALID = Bit 15 of CFSR",
    "Bật cờ bẫy lỗi chia cho 0": "Enable divide-by-zero trap flag",
    "Dừng CPU để kỹ sư cắm que nạp ST-Link vào quan sát": "Halt CPU for debugging with ST-Link probe",
    "Ghi vào địa chỉ cấm": "Write to prohibited memory address",
    "Hàm phân tích khung ngăn xếp viết bằng ngôn ngữ C": "C stack frame analyzer function",
    "In toàn bộ thông tin điều tra án mạng của CPU:": "Print comprehensive CPU crash post-mortem report:",
    "Kiểm tra bit 2 của thanh ghi LR (EXC_RETURN)": "Check bit 2 of LR register (EXC_RETURN)",
    "Kiểm tra xem có địa chỉ truy cập cấm trong BFAR không": "Check if BFAR holds invalid access address",
    "Nếu bit 2 = 0: Ngăn xếp sử dụng là MSP": "If bit 2 = 0: Active stack pointer is MSP",
    "Nếu bit 2 = 1: Ngăn xếp sử dụng là PSP (Đang chạy trong Task FreeRTOS)": "If bit 2 = 1: Active stack pointer is PSP (Running in FreeRTOS Task)",
    "Vùng nhớ không tồn tại": "Invalid / Non-existent memory address",
    "Điểm dừng Breakpoint phần cứng": "Hardware breakpoint trap",
    "Đoạn mã Assembly đón đầu hàm ngắt HardFault_Handler": "Assembly preamble for HardFault_Handler",
    "Đèn LED cảnh báo sập chip": "LED warning for MCU crash",
    "ĐỊA CHỈ DÒNG CODE GÂY LỖI!": "ADDRESS OF FAULTING INSTRUCTION!",
}
