# -*- coding: utf-8 -*-
# Batch 1: Bai 01 to Bai 05

BATCH_MAP = {
    # Bai 01
    "Bật LED": "Turn on LED",
    "Bật LED (Active-Low)": "Turn on LED (Active-Low)",
    "Cấp xung nhịp GPIOC": "Enable GPIOC clock",
    "Cấp xung nhịp cho GPIOC": "Enable peripheral clock for GPIOC",
    "Cấu hình PC13: Output Push-Pull 2MHz": "Configure PC13: Output Push-Pull 2MHz",
    "Tắt LED": "Turn off LED",

    # Bai 02
    "1. Cấp xung clock cho PORT A và PORT C thông qua RCC_APB2ENR": "1. Enable clocks for PORT A and PORT C via RCC_APB2ENR",
    "1. Cấp xung nhịp cho GPIOA và GPIOC": "1. Enable clocks for GPIOA and GPIOC",
    "2. Cấu hình PC13: Output Push-Pull tốc độ 2MHz": "2. Configure PC13: Output Push-Pull at 2MHz speed",
    "2. Cấu hình chân PC13: Output Push-Pull 2MHz": "2. Configure PC13 pin: Output Push-Pull 2MHz",
    "3. Cấu hình PA0: Input with Pull-up": "3. Configure PA0: Input with Pull-up",
    "3. Cấu hình chân PA0: Input Pull-Up": "3. Configure PA0 pin: Input Pull-Up",
    "Ban đầu tắt LED (ghi mức 1)": "Initial state: turn off LED (write HIGH)",
    "Chờ cho người dùng nhả nút bấm để tránh đảo liên tục": "Wait for button release to prevent continuous toggling",
    "Chờ nhả phím": "Wait for key release",
    "Khai báo con trỏ Bit-Banding trực tiếp": "Declare direct Bit-Banding pointer",
    "Kiểm tra nút nhấn PA0 (bấm = 0 do kéo xuống GND)": "Check button PA0 (pressed = LOW via GND connection)",
    "Lọc chống rung phím": "Button debounce filter",
    "Macro Bit-Banding cho vùng nhớ ngoại vi": "Bit-Banding macro for peripheral region",
    "Mặc định tắt LED": "Default: turn off LED",
    "ODR0 = 1 -> Kích hoạt điện trở PULL-UP nội": "ODR0 = 1 -> Enable internal PULL-UP resistor",
    "PC13 = 0 -> Bật LED": "PC13 = 0 -> Turn on LED",
    "PC13 = 1 -> Tắt LED": "PC13 = 1 -> Turn off LED",
    "Trễ chống rung khi nhả phím": "Button release debounce delay",
    "Trễ chống rung phím (Debounce)": "Key debounce delay",
    "Xác nhận chắc chắn nút vẫn đang được giữ": "Confirm button is still held down",
    "Xóa bit [23:20]": "Clear bits [23:20]",
    "Xóa bit [3:0]": "Clear bits [3:0]",
    "Đảo trạng thái LED PC13 bằng Bit-Banding nguyên tử": "Toggle LED PC13 atomically using Bit-Banding",
    "Đảo trạng thái PC13 bằng cách đọc ODR và ghi ngược lại": "Toggle PC13 by reading ODR and writing inverted state",
    "Đọc ODR -> Thực hiện OR bit -> Ghi ngược lại ODR": "Read ODR -> Perform bitwise OR -> Write back to ODR",
    "Đọc giá trị ngõ vào PA0": "Read PA0 input state",

    # Bai 03
    "1. Bật nguồn dao động thạch anh ngoài HSE": "1. Enable external crystal oscillator (HSE)",
    "1. Cấp clock cho GPIOA": "1. Enable clock for GPIOA",
    "1. Kích hoạt HSE": "1. Enable HSE",
    "2. Chờ thạch anh ngoài sẵn sàng (HSERDY)": "2. Wait until HSE is ready (HSERDY)",
    "2. Cấu hình PA8: Alternate Function Output Push-Pull 50MHz": "2. Configure PA8: Alternate Function Output Push-Pull 50MHz",
    "2. Kích hoạt Prefetch Buffer & thiết lập 2 Wait States": "2. Enable Prefetch Buffer & set 2 Wait States",
    "3. Chọn nguồn xuất ra MCO trong RCC_CFGR:": "3. Select MCO output clock source in RCC_CFGR:",
    "3. Cấu hình Flash Latency = 2 chu kỳ chờ và bật Prefetch Buffer": "3. Configure Flash Latency = 2 wait states and enable Prefetch Buffer",
    "3. Cấu hình bus clock": "3. Configure bus clocks",
    "4. Cấu hình PLL: HSE * 9 = 72MHz": "4. Configure PLL: HSE * 9 = 72MHz",
    "4. Thiết lập các bộ chia AHB, APB1, APB2": "4. Set AHB, APB1, APB2 prescalers",
    "5. Bật PLL & Chờ cờ Ready": "5. Enable PLL & wait for Ready flag",
    "5. Cấu hình PLL: Nguồn từ HSE, nhân tần số lên 9 lần (8MHz * 9 = 72MHz)": "5. Configure PLL: HSE source, multiply by 9 (8MHz * 9 = 72MHz)",
    "6. Chuyển SYSCLK sang PLL": "6. Switch SYSCLK to PLL",
    "6. Kích hoạt bộ PLL và chờ ổn định": "6. Enable PLL and wait until stabilized",
    "7. Chọn PLL làm xung nhịp hệ thống (SYSCLK)": "7. Select PLL as system clock (SYSCLK)",
    "8. Chờ xác nhận chuyển đổi thành công từ cờ SWS": "8. Wait for successful clock switch confirmation via SWS bits",
    "APB1 = 36MHz (Tối đa)": "APB1 = 36MHz (Maximum)",
    "Bật clock GPIOC và cấu hình PC13 chớp tắt LED": "Enable GPIOC clock and configure PC13 to blink LED",
    "Chờ PLLRDY = 1": "Wait for PLLRDY = 1",
    "Cấu hình chân PA8 xuất xung SYSCLK / 2 hoặc HSE": "Configure PA8 to output SYSCLK / 2 or HSE",
    "Cấu hình vi điều khiển chạy 72MHz": "Configure MCU to run at 72MHz",
    "PLLMUL = 0111b (Hệ số nhân x9)": "PLLMUL = 0111b (Multiplier x9)",
    "PLLSRC = 1 (HSE làm đầu vào PLL)": "PLLSRC = 1 (HSE as PLL input source)",
    "PLLXTPRE = 0 (HSE không chia 2)": "PLLXTPRE = 0 (HSE not divided by 2)",
    "Reset khối RCC về cấu hình xuất xưởng": "Reset RCC to factory default configuration",
    "Xuất trực tiếp HSE 8MHz ra chân PA8": "Output 8MHz HSE directly to PA8 pin",
    "Xóa bit LATENCY": "Clear LATENCY bits",
    "Xóa bit PLLMUL": "Clear PLLMUL bits",
    "Xử lý sự cố: Nếu thạch anh ngoài hỏng, chip vẫn chạy bằng HSI 8MHz": "Fault fallback: If HSE fails, chip continues running on 8MHz HSI",
    "Ở tốc độ 72MHz, vòng lặp này xấp xỉ 1ms": "At 72MHz, this loop takes approximately 1ms",

    # Bai 04
    "1. Cấp clock cho GPIOA, GPIOC và AFIO": "1. Enable clocks for GPIOA, GPIOC, and AFIO",
    "1. Cấp xung clock cho GPIOA, GPIOC và bộ ghép kênh ngoại vi AFIO": "1. Enable clocks for GPIOA, GPIOC, and AFIO multiplexer",
    "2. Cấu hình PC13 làm Output Push-Pull 2MHz": "2. Configure PC13 as Output Push-Pull 2MHz",
    "2. Cấu hình chân PC13: Output Push-Pull": "2. Configure PC13 pin: Output Push-Pull",
    "3. Cấu hình PA0 làm Input Pull-up": "3. Configure PA0 as Input Pull-Up",
    "3. Cấu hình chân PA0: Input Pull-Up": "3. Configure PA0 pin: Input Pull-Up",
    "4. Kết nối EXTI Line 0 với chân GPIOA Pin 0": "4. Connect EXTI Line 0 to GPIOA Pin 0",
    "4. Ánh xạ chân PA0 vào đường ngắt EXTI0 thông qua thanh ghi AFIO_EXTICR1": "4. Map PA0 to EXTI0 interrupt line via AFIO_EXTICR1 register",
    "5. Cấu hình bắt cạnh xuống (Falling Edge Trigger) trên EXTI0": "5. Configure falling edge trigger on EXTI0",
    "5. Cấu hình đường ngắt EXTI Line 0": "5. Configure EXTI Line 0",
    "6. Bật mặt nạ ngắt trên đường EXTI0": "6. Enable interrupt mask on EXTI0 line",
    "6. Cấu hình bộ điều khiển ngắt NVIC": "6. Configure NVIC interrupt controller",
    "7. Cấu hình NVIC: Bật ngắt EXTI0 và đặt mức ưu tiên": "7. Configure NVIC: Enable EXTI0 interrupt and set priority",
    "Bit [3:0] của AFIO_EXTICR1: 0000b chọn Port A cho EXTI0": "Bits [3:0] of AFIO_EXTICR1: 0000b selects Port A for EXTI0",
    "Biến cờ đánh dấu sự kiện nút nhấn từ ngắt": "Flag variable signaling button press event from ISR",
    "Bật bắt cạnh xuống (Khi bấm nút PA0 kéo xuống GND)": "Enable falling edge trigger (when PA0 button is pressed to GND)",
    "BẮT BUỘC: Xóa cờ ngắt bằng cách ghi bit 1 vào thanh ghi PR": "MANDATORY: Clear interrupt flag by writing 1 to PR register",
    "Bắt cạnh xuống": "Falling edge trigger",
    "CPU hoàn toàn rảnh rỗi hoặc có thể vào chế độ Sleep (WFI)": "CPU is completely idle or can enter Sleep mode (WFI)",
    "Hàm phục vụ ngắt EXTI Line 0 (Tên hàm chuẩn theo bảng Vector trong startup_stm32f10x_md.s)": "EXTI Line 0 ISR (Standard function name per Vector Table in startup_stm32f10x_md.s)",
    "Kiểm tra cờ ngắt": "Check interrupt flag",
    "Kiểm tra cờ ngắt EXTI0": "Check EXTI0 interrupt flag",
    "Kéo điện trở Pull-up": "Enable internal pull-up resistor",
    "Kích hoạt ngắt trên NVIC": "Enable interrupt in NVIC",
    "Lệnh Wait For Interrupt: Đưa CPU vào chế độ ngủ tiết kiệm điện": "Wait For Interrupt instruction: Enter low-power Sleep mode",
    "Nhóm ngắt EXTI0 có số hiệu ngắt EXTI0_IRQn = 6": "EXTI0 interrupt vector number EXTI0_IRQn = 6",
    "Thư viện chứa các hàm cấu hình NVIC": "Library containing NVIC configuration functions",
    "Tắt bắt cạnh lên": "Disable rising edge trigger",
    "Vòng lặp rảnh rỗi chờ ngắt": "Idle loop waiting for interrupts",
    "Xóa cờ ngắt EXTI Line 0": "Clear EXTI Line 0 interrupt flag",
    "Đảo LED PC13": "Toggle LED PC13",
    "Đảo trạng thái LED PC13": "Toggle LED PC13 state",
    "Đảo trạng thái cờ báo": "Toggle event flag state",

    # Bai 05
    "Bật clock GPIOC và GPIOB": "Enable GPIOC and GPIOB clocks",
    "CPU tự do làm hàng loạt công việc khác ở đây mà không bị dừng lại một nano-giây nào!": "CPU is free to execute other tasks here without blocking for a single nanosecond!",
    "Chờ cho đến khi cờ COUNTFLAG được kéo lên 1 (bit 16)": "Wait until COUNTFLAG bit (bit 16) is set to 1",
    "Cấp xung nhịp cho PORT C": "Enable peripheral clock for PORT C",
    "Cấu hình nhịp ngắt 1ms tại 72MHz: LOAD = 71999": "Configure 1ms tick rate at 72MHz: LOAD = 71999",
    "Hàm Delay micro-giây chính xác tuyệt đối": "High-precision microsecond delay function",
    "Hàm Delay mili-giây": "Millisecond delay function",
    "Hàm chuẩn CMSIS: Tự động tính toán LOAD, bật ngắt và khởi động SysTick": "CMSIS standard function: Automatically configures LOAD, enables interrupt and starts SysTick",
    "Khởi tạo SysTick không dùng ngắt (dùng cờ COUNTFLAG)": "Initialize polling-based SysTick (using COUNTFLAG)",
    "Kích hoạt: Nguồn HCLK (bit 2 = 1), Cho phép ngắt TICKINT (bit 1 = 1), ENABLE (bit 0 = 1)": "Enable: HCLK source (bit 2 = 1), TICKINT enabled (bit 1 = 1), ENABLE (bit 0 = 1)",
    "Lỗi nếu giá trị nạp vượt quá 24-bit": "Error if reload value exceeds 24-bit range",
    "Nguồn HCLK 72MHz, Bật Timer": "72MHz HCLK clock source, Enable Timer",
    "SystemCoreClock là biến lưu tần số hệ thống (72000000)": "SystemCoreClock holds system frequency (72000000)",
    "Task 1: Điều khiển LED PC13 mỗi 500ms": "Task 1: Toggle LED PC13 every 500ms",
    "Task 2: Điều khiển LED PB0 nháy nhanh mỗi 100ms": "Task 2: Fast blink LED PB0 every 100ms",
    "Tắt SysTick": "Disable SysTick",
    "Tắt SysTick trước khi cấu hình": "Disable SysTick prior to configuration",
    "Xóa giá trị đếm hiện thời": "Clear current counter value",
    "Đảo trạng thái LED PB0": "Toggle LED PB0 state",
    "Đặt mức ưu tiên cho ngắt SysTick (Ưu tiên thấp nhất để nhường ngoại vi quan trọng)": "Set SysTick interrupt priority (Lowest priority to yield to critical peripherals)",
    "Định thời 1 giây": "1-second timer delay",
    "Ở 72MHz: Mỗi us cần 72 chu kỳ đếm": "At 72MHz: 72 clock cycles per microsecond",
}
