# -*- coding: utf-8 -*-
# Batch 4: Bai 16 to Bai 20

BATCH_MAP = {
    # Bai 16
    "- Chế độ Master: MSTR = 1": "- Master mode: MSTR = 1",
    "- Khung truyền 8-bit: DFF = 0": "- 8-bit data frame: DFF = 0",
    "- Quản lý chân NSS bằng phần mềm: SSM = 1, SSI = 1": "- Software NSS management: SSM = 1, SSI = 1",
    "- Tốc độ: PCLK2 (72MHz) / 8 = 9MHz (BR[2:0] = 010b)": "- Baud rate: PCLK2 (72MHz) / 8 = 9MHz (BR[2:0] = 010b)",
    "1. Cấp xung clock cho GPIOA và SPI1 trên bus APB2": "1. Enable clocks for GPIOA and SPI1 on APB2 bus",
    "2. Cấu hình chân PA4 (CS): Output Push-Pull 50MHz": "2. Configure PA4 (CS): Output Push-Pull 50MHz",
    "3. Cấu hình PA5 (SCK) và PA7 (MOSI): Alternate Function Output Push-Pull 50MHz": "3. Configure PA5 (SCK) and PA7 (MOSI): AF Output Push-Pull 50MHz",
    "4. Cấu hình PA6 (MISO): Input with Pull-Up": "4. Configure PA6 (MISO): Input with Pull-Up",
    "5. Cấu hình khối SPI1 trên thanh ghi SPI_CR1:": "5. Configure SPI1 in SPI_CR1 register:",
    "6. Kích hoạt bộ SPI1 (SPE = 1)": "6. Enable SPI1 peripheral (SPE = 1)",
    "Bắt đầu phiên truyền": "Start transmission session",
    "Chờ bộ đệm nhận có dữ liệu về (RXNE = 1)": "Wait until receive buffer has data (RXNE = 1)",
    "Chờ bộ đệm truyền trống (TXE = 1)": "Wait until transmit buffer is empty (TXE = 1)",
    "Chờ cờ BSY = 0 báo hiệu bus hoàn toàn rảnh rỗi": "Wait until BSY = 0 (bus completely idle)",
    "Cấu hình SPI1 Master Mode 0": "Configure SPI1 Master Mode 0",
    "Gửi Dummy byte 0xFF để nhận về 3 byte mã ID": "Send dummy byte 0xFF to receive 3-byte ID code",
    "Gửi mã lệnh đọc JEDEC ID: 0x9F": "Send JEDEC ID read command: 0x9F",
    "Hàm truyền và nhận đồng thời 1 byte dữ liệu qua SPI1": "Full-duplex transmit and receive 1 byte via SPI1",
    "Kiểm tra xem chip nhớ có phản hồi đúng 0xEF4017 hay không": "Verify memory chip responds with 0xEF4017",
    "Kết thúc phiên truyền": "End transmission session",
    "Mặc định không chọn chip (CS = 1)": "Default: deselect chip (CS = 1)",
    "Nhận diện chip nhớ W25Q64 thành công!": "W25Q64 Flash recognized successfully!",
    "Đọc mã ID của chip nhớ Flash ngoài": "Read external Flash memory ID code",
    "Đọc mã nhận dạng chip JEDEC ID của W25Q64": "Read W25Q64 JEDEC ID",

    # Bai 17
    "- DIR = 1: Đọc từ RAM ra Ngoại vi (Memory to Peripheral)": "- DIR = 1: Memory to Peripheral transfer",
    "- MINC = 1: Tự động tăng địa chỉ ô nhớ RAM": "- MINC = 1: Memory increment mode enabled",
    "- PINC = 0: Không tăng địa chỉ ngoại vi": "- PINC = 0: Peripheral increment mode disabled",
    "- PL = 10b (Mức ưu tiên High)": "- PL = 10b (High priority level)",
    "1. Cấp clock cho GPIOA, USART1 và khối DMA1 trên bus AHB": "1. Enable clocks for GPIOA, USART1, and DMA1 on AHB bus",
    "1. Cấp xung clock cho GPIOA, ADC1 và DMA1": "1. Enable clocks for GPIOA, ADC1, and DMA1",
    "2. Cấu hình chân PA9 (TX): Alternate Function Push-Pull 50MHz": "2. Configure PA9 (TX): Alternate Function Push-Pull 50MHz",
    "2. PA0 và PA1: Analog Mode": "2. PA0 and PA1: Analog Mode",
    "3 phần tử": "3 elements",
    "3. CẤU HÌNH DMA1 CHANNEL 1 (GẮN LIỀN VỚI ADC1)": "3. CONFIGURE DMA1 CHANNEL 1 (MAPPED TO ADC1)",
    "3. Cấu hình Baudrate USART1 = 115200 (72MHz)": "3. Configure USART1 Baudrate = 115200 (72MHz)",
    "4. Cho phép USART1 phát yêu cầu truyền DMA (DMAT = 1 trong USART_CR3)": "4. Enable USART1 DMA transmitter (DMAT = 1 in USART_CR3)",
    "4. CẤU HÌNH ADC1 CHẾ ĐỘ QUÉT LIÊN TỤC (SCAN CONV MODE)": "4. CONFIGURE ADC1 CONTINUOUS SCAN CONVERSION MODE",
    "5. Cấu hình DMA1 Channel 4 (chuyên trách USART1_TX):": "5. Configure DMA1 Channel 4 (dedicated for USART1_TX):",
    "BẬT QUÉT ĐA KÊNH": "ENABLE SCAN MODE",
    "Bật kênh DMA để bắt đầu tự động truyền": "Enable DMA channel to start transfer",
    "Bắt đầu chuyển đổi chuỗi": "Start sequence conversion",
    "CHUYỂN ĐỔI LIÊN TỤC": "CONTINUOUS CONVERSION",
    "CPU chỉ cần đọc trực tiếp dữ liệu từ mảng RAM bất kỳ lúc nào:": "CPU can directly read data from RAM array at any time:",
    "CPU hoàn toàn rảnh rỗi chớp tắt LED PC13 mà không bị nghẽn": "CPU is completely free to blink PC13 without blocking",
    "Cho phép ADC1 kích phát yêu cầu truyền dữ liệu sang DMA": "Enable ADC1 DMA request generation",
    "Cấu hình thanh ghi CCR4:": "Configure CCR4 register:",
    "DMA1EN = 1 (Bật clock DMA1)": "DMA1EN = 1 (Enable DMA1 clock)",
    "Kích hoạt ADC1 và Hiệu chuẩn": "Enable ADC1 and perform Calibration",
    "Kích hoạt DMA1 Channel 1": "Enable DMA1 Channel 1",
    "Kích hoạt cảm biến nhiệt độ nội": "Enable internal temperature sensor",
    "Ngoại vi -> RAM": "Peripheral to Memory",
    "Nhiệt độ nội": "Internal temperature",
    "Nạp lại độ dài chuỗi": "Reload sequence length",
    "Số lượng byte cần truyền": "Number of data bytes to transfer",
    "Thứ tự 1: Channel 0 (PA0)": "Rank 1: Channel 0 (PA0)",
    "Thứ tự 2: Channel 1 (PA1)": "Rank 2: Channel 1 (PA1)",
    "Thứ tự 3: Channel 16 (Nhiệt độ nội - 239.5 chu kỳ)": "Rank 3: Channel 16 (Internal temperature - 239.5 cycles)",
    "Tăng mảng RAM": "Increment RAM address pointer",
    "Tắt kênh trước khi cấu hình": "Disable channel before configuration",
    "Tắt kênh để nạp lại số lượng dữ liệu": "Disable channel to reload buffer length",
    "VÒNG TRÒN KHÉP KÍN": "CIRCULAR BUFFER MODE",
    "Xóa cờ hoàn thành truyền cũ trong DMA_IFCR": "Clear legacy transfer complete flags in DMA_IFCR",
    "Điện áp PA0": "PA0 voltage",
    "Điện áp PA1": "PA1 voltage",
    "Địa chỉ bộ nhớ RAM: Con trỏ trỏ tới chuỗi ký tự": "Memory address: Pointer to string buffer",
    "Địa chỉ ngoại vi: Thanh ghi dữ liệu USART1_DR (0x40013804)": "Peripheral address: USART1_DR register (0x40013804)",
    "Định nghĩa thứ tự chuỗi đo:": "Define measurement sequence order:",

    # Bai 18
    "1. Cấp xung clock cho khối điều khiển nguồn PWR và khối lưu trữ BKP": "1. Enable clocks for PWR controller and BKP backup registers",
    "2. Kích hoạt tính năng chân Wakeup Pin (PA0) trong thanh ghi PWR_CSR": "2. Enable Wakeup Pin (PA0) functionality in PWR_CSR",
    "3. Xóa các cờ trạng thái Wakeup và Standby cũ": "3. Clear legacy Wakeup and Standby status flags",
    "4. Chọn chế độ Standby trong PWR_CR": "4. Select Standby mode in PWR_CR",
    "5. Cấu hình lõi Cortex-M3 cho phép Deep Sleep": "5. Configure Cortex-M3 core for Deep Sleep mode",
    "6. Thực thi lệnh hợp ngữ WFI để đưa vi điều khiển vào giấc ngủ sâu lập tức": "6. Execute WFI assembly instruction to enter deep sleep immediately",
    "Bật clock PWR để kiểm tra cờ trạng thái": "Enable PWR clock to check status flags",
    "BẮT BUỘC PHẢI KHỞI ĐỘNG LẠI HSE VÀ PLL ĐỂ ĐƯA CPU VỀ LẠI 72MHz:": "MANDATORY: RESTORE HSE AND PLL TO RETURN CPU TO 72MHz:",
    "Chờ 3 giây trước khi ngủ": "Wait 3 seconds before sleeping",
    "Cấu hình LED PC13": "Configure LED PC13",
    "Dòng lệnh này sẽ không bao giờ được thực thi vì CPU đã ngủ": "This line is never reached as CPU has entered sleep",
    "Khởi động lần đầu do cắm nguồn: Nháy LED chậm": "First startup via power-on: Slow LED blink",
    "Kiểm tra xem lần khởi động này có phải do thức dậy từ Standby Mode không": "Check if startup was triggered by Standby Mode wakeup",
    "LƯU Ý SỐNG CÒN: KHI VỪA THỨC DẬY TỪ STOP MODE, HỆ THỐNG MẶC ĐỊNH CHẠY BẰNG HSI 8MHz!": "CRITICAL NOTE: UPON WAKING FROM STOP MODE, SYSTEM RUNS ON 8MHz HSI BY DEFAULT!",
    "Thức dậy từ Standby: Nháy LED cực nhanh": "Waking from Standby: Rapid LED blink",
    "Đưa chip vào Stop Mode với bộ điều chỉnh điện áp ở chế độ Low Power": "Enter Stop Mode with voltage regulator in Low Power mode",
    "Đưa chip vào chế độ Standby Mode": "Put MCU into Standby Mode",
    "Để đánh thức: Nối chân PA0 lên 3.3V": "To wakeup: Connect PA0 pin to 3.3V",

    # Bai 19
    "... [Khởi tạo USART1 như Bài 13] ...": "... [Initialize USART1 as in Lesson 13] ...",
    "1. Đọc số lần khởi động hiện tại từ Flash": "1. Read current boot counter from Flash",
    "2. Mở khóa Flash và cập nhật giá trị mới": "2. Unlock Flash and update new value",
    "BẮT BUỘC: Xóa trang trước khi ghi dữ liệu mới": "MANDATORY: Erase page before programming new data",
    "Chờ cờ BSY = 0": "Wait until BSY flag = 0",
    "Chờ ghi xong": "Wait for programming completion",
    "Chờ thao tác Flash hoàn tất": "Wait for Flash operation completion",
    "Chờ xóa xong": "Wait for erase completion",
    "Cấu hình UART để in log debug (Baudrate 115200)": "Configure UART for debug logs (Baudrate 115200)",
    "Ghi Khóa 1": "Write Key 1",
    "Ghi Khóa 2": "Write Key 2",
    "Ghi dữ liệu 16-bit trực tiếp qua con trỏ": "Write 16-bit data directly via pointer",
    "Ghi giá trị boot_counter mới vào Flash": "Write new boot_counter value to Flash",
    "Ghi một mảng dữ liệu 16-bit vào Flash": "Program a 16-bit array into Flash",
    "Ghi tuần tự từng Half-Word (16-bit)": "Program sequentially half-word by half-word (16-bit)",
    "In thông báo ra màn hình": "Print message to console",
    "Khóa Flash": "Lock Flash",
    "Khóa lại Flash": "Relock Flash",
    "Khóa lại Flash để đảm bảo an toàn tuyệt đối": "Relock Flash to ensure absolute memory safety",
    "Mở khóa Flash": "Unlock Flash",
    "Nạp địa chỉ trang cần xóa": "Load target page erase address",
    "Nếu Flash đang bị khóa (Bit 7 LOCK = 1)": "If Flash is locked (Bit 7 LOCK = 1)",
    "Nếu trang vừa bị xóa trắng (chứa 0xFFFF), gán lại bằng 0": "If erased page contains 0xFFFF, reinitialize to 0",
    "STRT = 1 (Bắt đầu xóa)": "STRT = 1 (Start page erase)",
    "Tăng số lần khởi động lên 1": "Increment boot counter by 1",
    "Tắt chế độ xóa trang PER = 0": "Disable page erase mode (PER = 0)",
    "Xóa 1 trang Flash (1KB)": "Erase 1 Flash page (1KB)",
    "Xóa cờ trạng thái cũ": "Clear legacy status flags",
    "Xóa trang": "Erase page",
    "Địa chỉ bắt đầu của Page 63 (1KB cuối cùng)": "Base address of Page 63 (Last 1KB)",
    "Đọc dữ liệu từ Flash (Đơn giản là đọc qua con trỏ nhớ thông thường)": "Read data from Flash (Direct reading via memory pointer)",

    # Bai 20
    "1. Tên hàm thực thi Task": "1. Task function pointer",
    "1. Định nghĩa Task 1: Điều khiển LED PC13": "1. Task 1 definition: Toggle LED PC13",
    "2. Tên mô tả Task (dùng cho debug)": "2. Descriptive task name (for debugging)",
    "2. Định nghĩa Task 2: Điều khiển LED PB0": "2. Task 2 definition: Control LED PB0",
    "3. Kích thước Stack (tính theo số Word 32-bit: 128 words = 512 bytes)": "3. Stack depth (in 32-bit words: 128 words = 512 bytes)",
    "4. Tham số truyền vào Task (NULL nếu không dùng)": "4. Task parameters (NULL if unused)",
    "5. Mức độ ưu tiên (Priority: Số càng lớn độ ưu tiên càng cao)": "5. Task priority (Higher value = higher priority)",
    "6. Con trỏ TaskHandle (NULL nếu không cần quản lý từ xa)": "6. Task handle pointer (NULL if unneeded)",
    "Biến lưu mốc thời gian để delay chính xác tuyệt đối": "Timestamp variable for exact periodic delay",
    "Bật LED PB0": "Turn on LED PB0",
    "Bật clock GPIOC và GPIOB": "Enable GPIOC and GPIOB clocks",
    "Dòng lệnh dưới đây sẽ không bao giờ được chạm tới trừ khi bị tràn RAM (Heap out of memory)": "The code below is never reached unless heap memory is exhausted",
    "Hàm này sẽ tự động được gọi nếu phát hiện Task bị tràn Stack!": "Hook called automatically upon detecting Task stack overflow!",
    "KHỞI ĐỘNG BỘ LẬP LỊCH FREERTOS SCHEDULER": "START FREERTOS SCHEDULER",
    "Khai báo các thư viện FreeRTOS cốt lõi": "Core FreeRTOS headers",
    "Khởi tạo phần cứng ngoại vi": "Initialize peripheral hardware",
    "Ngủ 100ms": "Sleep 100ms",
    "Tham số:": "Parameters:",
    "TẠO CÁC TASK TRONG HỆ ĐIỀU HÀNH BẰNG HÀM xTaskCreate()": "CREATE OS TASKS USING xTaskCreate()",
    "Tắt LED PB0": "Turn off LED PB0",
    "Từ dòng này trở đi, quyền điều khiển CPU hoàn toàn thuộc về FreeRTOS!": "From here onwards, CPU execution is governed by FreeRTOS!",
    "Đưa Task vào trạng thái Blocked đúng 500ms, giải phóng CPU 100%": "Block task for 500ms, releasing 100% CPU time",
    "Đảo trạng thái LED PC13": "Toggle LED PC13 state",
    "Đổi 500ms sang ticks": "Convert 500ms to tick counts",
}
